<a href="https://colab.research.google.com/github/SaraMuayad/Electropi_AI_Projects/blob/main/Practice_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

1. Import numpy library

In [2]:
import numpy as np

3. Create an array to have 10 ones

In [12]:
array_ones = np.ones(10)
array_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

4. Create an array to have 10 fives

In [11]:
array_fives = np.full(10,5)
array_fives

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

5. Create an array contain numbers from 10 to 50

In [10]:
array_between = np.arange(10,51)
array_between

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

6. Create an array of even numbers between 10 to 50

In [9]:
array_even_number = np.arange(10,51,2)
array_even_number

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

7. Create a matrix (3x3) from numbers 0 to 8

In [13]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

8. create a matrix (3x3) with random numbers

In [19]:
random_mat = np.random.rand(3, 3)
random_mat

array([[0.8412147 , 0.83350836, 0.59532751],
       [0.50256692, 0.53224019, 0.30233913],
       [0.4704027 , 0.26900119, 0.40877976]])

9. Create a matrix (3x3) with standard normal random numbers around zero value

In [93]:
normal_matrix = np.random.randn(3, 3)
print(normal_matrix)

[[ 0.89205752  0.70442993 -0.95097753]
 [ 0.25808053  0.98668283 -1.75917448]
 [ 1.001037    1.1016197   0.52756569]]


In [92]:
arr_matrix = np.arange(0.01, 1.01, 0.01)
matrix = arr_matrix.reshape(10, 10)
matrix = matrix.reshape(10, 10)
print(matrix)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [91]:
matrix = []
value = 0.01
for i in range(10):
    row = []
    for j in range(10):
        row.append(round(value, 2))
        value += 0.01
    matrix.append(row)


matrix_two = np.array(matrix)
matrix_two

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

11. Create an array include 20 numbers with equal distance between zero and one

In [22]:
linspace_array = np.linspace(0, 1, 20)
linspace_array

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

12. first create the following matrix and then find the following subsections of the array

In [23]:
mat =np.array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [24]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [28]:
mat[2:5, 1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [87]:
mat[3,4]
print(mat[3,4])

20


In [34]:
mat[0:3,1:2].reshape(1,3)

array([[ 2,  7, 12]])

In [38]:
mat[4:5]

array([[21, 22, 23, 24, 25]])

In [40]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [61]:
mat[[0, 2, 4], :]


array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [41]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [62]:
mat[:, [0, 2, 4]]

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20],
       [21, 23, 25]])

In [63]:
mat[0:5:2, 0:5:2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

In [65]:
mat[0:5:2, 0:5:2].T

array([[ 1, 11, 21],
       [ 3, 13, 23],
       [ 5, 15, 25]])

13. sum up all elements of the matrix with two ways: 1- an universal function 'sum', 2- via programming

In [68]:
sumation = np.sum(mat)
print(sumation)

325


In [69]:
sumation = 0
for row in mat:
    for element in row:
        sumation += element

print(sumation)

325


14. find average of numbers inside the mat matrix using universal 'mean' function and also standard deviation using universal 'std' function

In [70]:
mean = np.mean(mat)
print(mean)

13.0


In [71]:
standard_dev = np.std(mat)
print(standard_dev)

7.211102550927978


15. via google, search about 'axis' in numpy and find the defualt value for 'axis' in numpy. Next find the sumup rows and sumup columns using 'axis'

sum of rows:

In [ ]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [77]:
row_sums = np.sum(mat, axis=1).reshape(5,1)
row_sums

array([[ 15],
       [ 40],
       [ 65],
       [ 90],
       [115]])

16. sum of rows with function

In [79]:
sum_of_row = np.sum(mat, axis=1)
sum_of_row

array([ 15,  40,  65,  90, 115])

17. sum of columns

In [80]:
sum_of_columns = np.sum(mat,axis=0)
sum_of_columns

array([55, 60, 65, 70, 75])

18. now you have searched about 'axis' concept in internet, using 'concatenate' and 'axis' concatenate following two matricies in both horizental and vertical axes

In [82]:

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:

b = np.array([[1,4,7],[2,5,8],[3,6,9]])
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [85]:
horizontal = np.concatenate((a, b), axis=1)
horizontal

array([[1, 2, 3, 1, 4, 7],
       [4, 5, 6, 2, 5, 8],
       [7, 8, 9, 3, 6, 9]])

In [86]:
vertical = np.concatenate((a, b), axis=0)
vertical

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Good Luck

Abdulhady Abas